[tool.poetry]
name = "roses"
version = "0.0.0"
description = ""
authors = ["Melnik Fedor"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scikit-learn = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
